---
include:
  # Colemak-DH
  - board: nice_nano_v2
    shield: corne_eclipse_left eclipse_nice_view_adapter_trrs nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: left_corne_eclipse_colemak_dh.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right eclipse_nice_view_adapter_trrs nice_view
    artifact-name: right_corne_eclipse_colemak_dh_encoder_or_switch.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right
    cmake-args: -DCONFIG_INPUT_AZOTEQ_IQS5XX=y -DCONFIG_ZMK_DISPLAY=n -DDTS_EXTRA_CPPFLAGS="-DUSE_TRACKPAD_AZOTEQ=1"
    artifact-name: right_corne_eclipse_colemak_dh_azoteq_trackpad_and_switch.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right
    cmake-args: -DCONFIG_INPUT_PINNACLE=y -DCONFIG_I2C=y -DCONFIG_ZMK_DISPLAY=n -DDTS_EXTRA_CPPFLAGS="-DUSE_TRACKPAD_CIRQUE=1"
    artifact-name: right_corne_eclipse_colemak_dh_cirque_trackpad_and_switch.zmk

  # QWERTY
  - board: nice_nano_v2
    shield: corne_eclipse_left eclipse_nice_view_adapter_trrs nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DDTS_EXTRA_CPPFLAGS="-DDEFAULT_TYPING_LAYER=1"
    artifact-name: left_corne_eclipse_qwerty.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right eclipse_nice_view_adapter_trrs nice_view
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DDEFAULT_TYPING_LAYER=1"
    artifact-name: right_corne_eclipse_qwerty_encoder_or_switch.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right
    cmake-args: -DCONFIG_INPUT_AZOTEQ_IQS5XX=y -DCONFIG_ZMK_DISPLAY=n "-DDTS_EXTRA_CPPFLAGS=-DDEFAULT_TYPING_LAYER=1;-DUSE_TRACKPAD_AZOTEQ=1"
    artifact-name: right_corne_eclipse_qwerty_azoteq_trackpad_and_switch.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right
    cmake-args: -DCONFIG_INPUT_PINNACLE=y -DCONFIG_I2C=y -DCONFIG_ZMK_DISPLAY=n "-DDTS_EXTRA_CPPFLAGS=-DDEFAULT_TYPING_LAYER=1;-DUSE_TRACKPAD_CIRQUE=1"
    artifact-name: right_corne_eclipse_qwerty_cirque_trackpad_and_switch.zmk

  # Dvorak
  - board: nice_nano_v2
    shield: corne_eclipse_left eclipse_nice_view_adapter_trrs nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DDTS_EXTRA_CPPFLAGS="-DDEFAULT_TYPING_LAYER=2"
    artifact-name: left_corne_eclipse_dvorak.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right eclipse_nice_view_adapter_trrs nice_view
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DDEFAULT_TYPING_LAYER=2"
    artifact-name: right_corne_eclipse_dvorak_encoder_or_switch.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right
    cmake-args: -DCONFIG_INPUT_AZOTEQ_IQS5XX=y -DCONFIG_ZMK_DISPLAY=n "-DDTS_EXTRA_CPPFLAGS=-DDEFAULT_TYPING_LAYER=2;-DUSE_TRACKPAD_AZOTEQ=1"
    artifact-name: right_corne_eclipse_dvorak_azoteq_trackpad_and_switch.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right
    cmake-args: -DCONFIG_INPUT_PINNACLE=y -DCONFIG_I2C=y -DCONFIG_ZMK_DISPLAY=n "-DDTS_EXTRA_CPPFLAGS=-DDEFAULT_TYPING_LAYER=2;-DUSE_TRACKPAD_CIRQUE=1"
    artifact-name: right_corne_eclipse_dvorak_cirque_trackpad_and_switch.zmk

  # Workman
  - board: nice_nano_v2
    shield: corne_eclipse_left eclipse_nice_view_adapter_trrs nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DDTS_EXTRA_CPPFLAGS="-DDEFAULT_TYPING_LAYER=3"
    artifact-name: left_corne_eclipse_workman.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right eclipse_nice_view_adapter_trrs nice_view
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DDEFAULT_TYPING_LAYER=3"
    artifact-name: right_corne_eclipse_workman_encoder_or_switch.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right
    cmake-args: -DCONFIG_INPUT_AZOTEQ_IQS5XX=y -DCONFIG_ZMK_DISPLAY=n "-DDTS_EXTRA_CPPFLAGS=-DDEFAULT_TYPING_LAYER=3;-DUSE_TRACKPAD_AZOTEQ=1"
    artifact-name: right_corne_eclipse_workman_azoteq_trackpad_and_switch.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right
    cmake-args: -DCONFIG_INPUT_PINNACLE=y -DCONFIG_I2C=y -DCONFIG_ZMK_DISPLAY=n "-DDTS_EXTRA_CPPFLAGS=-DDEFAULT_TYPING_LAYER=3;-DUSE_TRACKPAD_CIRQUE=1"
    artifact-name: right_corne_eclipse_workman_cirque_trackpad_and_switch.zmk

  # Colemak
  - board: nice_nano_v2
    shield: corne_eclipse_left eclipse_nice_view_adapter_trrs nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DDTS_EXTRA_CPPFLAGS="-DDEFAULT_TYPING_LAYER=4"
    artifact-name: left_corne_eclipse_colemak.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right eclipse_nice_view_adapter_trrs nice_view
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DDEFAULT_TYPING_LAYER=4"
    artifact-name: right_corne_eclipse_colemak_encoder_or_switch.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right
    cmake-args: -DCONFIG_INPUT_AZOTEQ_IQS5XX=y -DCONFIG_ZMK_DISPLAY=n "-DDTS_EXTRA_CPPFLAGS=-DDEFAULT_TYPING_LAYER=4;-DUSE_TRACKPAD_AZOTEQ=1"
    artifact-name: right_corne_eclipse_colemak_azoteq_trackpad_and_switch.zmk
  - board: nice_nano_v2
    shield: corne_eclipse_right
    cmake-args: -DCONFIG_INPUT_PINNACLE=y -DCONFIG_I2C=y -DCONFIG_ZMK_DISPLAY=n "-DDTS_EXTRA_CPPFLAGS=-DDEFAULT_TYPING_LAYER=4;-DUSE_TRACKPAD_CIRQUE=1"
    artifact-name: right_corne_eclipse_colemak_cirque_trackpad_and_switch.zmk
